ComplianceManagement.Portal/Areas/BM_Management/Controllers/DirectorMeetingsController.cs
using BM_ManegmentServices.Data;
using BM_ManegmentServices.Services.DirectorMeetings;
using BM_ManegmentServices.Services.Googleservices;
using BM_ManegmentServices.Services.Meetings;
using BM_ManegmentServices.VM;
using BM_ManegmentServices.VM.Dashboard;
using com.VirtuosoITech.ComplianceManagement.Portal.Common;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Auth.OAuth2.Flows;
using Google.Apis.Auth.OAuth2.Responses;
using Google.Apis.Calendar.v3;
using Google.Apis.Services;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace com.VirtuosoITech.ComplianceManagement.Portal.Areas.BM_Management.Controllers
{
    public class DirectorMeetingsController : Controller
    {
        Compliance_SecretarialEntities entities = new Compliance_SecretarialEntities();
        IDirectorMeetings _objdirectorMeeting;
        IMainMeeting obj;
        public DirectorMeetingsController(IDirectorMeetings _objdirectorMeeting, IMainMeeting obj)
        {
            this._objdirectorMeeting = _objdirectorMeeting;
            this.obj = obj;
        }

        public static string[] Scopes =
        {
                                CalendarService.Scope.Calendar,
                                CalendarService.Scope.CalendarReadonly
                            };
        // GET: BM_Management/DirectorMeetings
        int userId = AuthenticationHelper.UserID;
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UpcomingMeetings()
        {
            return View();
        }

        public ActionResult SeekAvailibility()
        {
            return View();
        }
        public ActionResult CircularResolution()
        {
            return View();
        }
        public ActionResult PastCircularResolution()
        {
            return View();
        }
        public ActionResult Meetings_Read_Participants([DataSourceRequest] DataSourceRequest request, long MeetingId)
        {
            int customerId = Convert.ToInt32(AuthenticationHelper.CustomerID);
            return null;//Json(_objdirectorMeeting.GetMeetingParticipants(MeetingId).ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        #region Created by Ruchi on 5th of May 2020 SeekAvability

        public ActionResult UpdateAvailability(string meetingAviability)
        {
            if (meetingAviability != null)
            {
                var model = JsonConvert.DeserializeObject<List<Aviability>>(meetingAviability);

                IEnumerable<MeetingVM> objmeetingvm = new List<MeetingVM>();
                int UserID = Convert.ToInt32(AuthenticationHelper.UserID);
                if (model.Count > 0)
                {
                    foreach (var item in model)
                    {
                        var obj = _objdirectorMeeting.UpdateSeekaviabilityResponses(item, UserID);
                    }
                }
            }
            return Json(meetingAviability, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Getdetailsofseekava([DataSourceRequest] DataSourceRequest request)
        {
            int UserID = Convert.ToInt32(AuthenticationHelper.UserID);
            return Json(_objdirectorMeeting.GetPedingAvailability(UserID).ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }
        #endregion Created by Ruchi on 5th of May 2020

        #region Created by Ruchi on 5th of May 2020 Upcomming Meeting
        public ActionResult upcommingMeeting()
        {
            return View();
        }

        public ActionResult UpcommingMetting([DataSourceRequest] DataSourceRequest request)
        {
            int customerId = Convert.ToInt32(AuthenticationHelper.CustomerID);
            int userID = Convert.ToInt32(AuthenticationHelper.UserID);
            var role = AuthenticationHelper.Role;
            var result = _objdirectorMeeting.GetMeetingsForUpcommingMeeting(userID, customerId, AuthenticationHelper.Role);
            return Json(result.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }


        public ActionResult updateUpcommingresponse(MeetingListVM _objmeetingvm)
        {
            var result = _objdirectorMeeting.saveupdateupcomingMeetingdtlsbydir(_objmeetingvm, userId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        public ActionResult MarkAttendence(long MeetingId, long ParticipantId)
        {
            int UserId = AuthenticationHelper.UserID;
            bool result = false;
            if (MeetingId > 0 && ParticipantId > 0)
            {
                result = _objdirectorMeeting.MarkAttendence(MeetingId, ParticipantId, UserId);
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        #endregion Created by Ruchi on 5th of May 2020 Upcomming Meeting

        #region Created by Ruchi on 22nd of May 2020 Circural Resolution
        public ActionResult GetCircularResolution([DataSourceRequest] DataSourceRequest request)
        {
            int customerId = Convert.ToInt32(AuthenticationHelper.CustomerID);
            int userID = Convert.ToInt32(AuthenticationHelper.UserID);
            var role = AuthenticationHelper.Role;
            var result = _objdirectorMeeting.GetCircularResolution(userID, customerId, AuthenticationHelper.Role);
            return Json(result.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetPastCircularresolution([DataSourceRequest] DataSourceRequest request)
        {
            int customerId = Convert.ToInt32(AuthenticationHelper.CustomerID);
            int userID = Convert.ToInt32(AuthenticationHelper.UserID);
            var role = AuthenticationHelper.Role;
            var result = _objdirectorMeeting.GetPastCircularResolution(userID, customerId, AuthenticationHelper.Role);
            return Json(result.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }
        public ActionResult AgendaDetailswithvotingnoting([DataSourceRequest] DataSourceRequest request, long MeetingId)
        {
            List<MeetingAgendaSummary> _objagendadeals = new List<MeetingAgendaSummary>();

            _objagendadeals = obj.GetAgendaMeetingwise(MeetingId, userId);

            return Json(_objagendadeals.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }


        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult AddUpdateCircularResponses([DataSourceRequest] DataSourceRequest request, [Bind(Prefix = "models")] IEnumerable<MeetingAgendaSummary> _objagendaresponse)
        {
            var results = new MeetingAgendaSummary();

            if (_objagendaresponse != null && ModelState.IsValid)
            {
                foreach (var vottings in _objagendaresponse)
                {
                    vottings.userID = AuthenticationHelper.UserID;
                    results = _objdirectorMeeting.AddCircularVotting(vottings);
                }
            }

            return Json("success", JsonRequestBehavior.AllowGet);
        }

        #endregion Created by Ruchi on 22nd of May 2020 Circural Resolution

        public ActionResult Createcalenderresponse(long Id)
        {
            var getMeetingDate = (from row in entities.BM_Meetings
                                  where row.MeetingID == Id
                                  select new MeetingDetailsforCal
                                  {
                                      MeetingDate = row.MeetingDate,
                                      MeetingId = row.MeetingID,
                                      MeetingType = row.BM_CommitteeComp.MeetingTypeName,
                                      venu = row.MeetingVenue,
                                      MeetingTitle = row.MeetingTime,
                                  }).FirstOrDefault();
            TempData["MeetingDetails"] = new MeetingDetailsforCal { MeetingDate = getMeetingDate.MeetingDate, MeetingType = getMeetingDate.MeetingType, venu = getMeetingDate.venu };
            if (string.IsNullOrWhiteSpace(GoogleOauthTokenService.OauthToken))
            {
                var redirectUri = GoogleCalendarSyncer.GetOauthTokenUri(this);
                return Redirect(redirectUri);
            }
            else
            {
                var success = GoogleCalendarSyncer.SyncToGoogleCalendar(this);
                if (!success)
                {
                    return Json("Token was revoked. Try again.");
                }
            }
            //return Redirect("BM_Management/DirectorMeetings/UpcomingMeetings");
            return Redirect(Request.UrlReferrer.ToString());
        }

    }
}

ComplianceManagement.Portal/Areas/BM_Management/Views/DirectorMeetings/SeekAvailibility.cshtml
@using Kendo.Mvc.UI;

@{
    ViewBag.Title = "Seek Availability";
}

<style>
    #SeekAviabilityMeeting .k-grid-header {
        height: 0;
        border-bottom-width: 0;
        display: none;
        overflow: hidden;
    }

    .mt-1 {
        margin-top: 1%;
    }

    .seekavabtn {
        width: 11%;
        height: 25px;
        left: 1399px;
        top: 122px;
        background: #0090D6;
        border-radius: 5px;
    }

    .checkcalender {
      
        height: 25px;
        left: 1399px;
        top: 122px;
        background: #0090D6;
        border-radius: 5px;
    }

    .container .checkmarkava:after {
        left: 4px;
        top: 0px;
        width: 6px;
        height: 13px;
        border: solid #1976d2;
        border-width: 0 3px 3px 0;
        -webkit-transform: rotate(45deg);
        -ms-transform: rotate(45deg);
        transform: rotate(45deg);
    }
</style>

<script>

    $(document).ready(function () {

        var breadCrumbData = [
            {
                displayText: "My Workspace",
                navigateUrl: "#",
            },
            {
                displayText: "Seek Availability",
                navigateUrl: "#",
            }
        ];

        setBreadCrumb(breadCrumbData);
    });

    setBreadCrumb(breadCrumbData);

    function checkcalender(obj)
    {
        location.href = '@Url.Action("Createcalenderresponse", "DirectorMeetings")';
    }
    function setDataItemforavlonMeeting(item)
    {
        
        var j;
        var grid = $("#SeekAviabilityMeeting").data("kendoGrid");
        var row = $(item).closest("tr")
        var dataItem = grid.dataItem(row);

        for (j = 0; j < dataItem.MeetingAviability.length > 0; j++)
        {
            var currentitem=$("#"+item.id);
            var id='#'+j+dataItem.uid+'_checkbox';
            if (currentitem.selector == id)
            {
                if ($(item).is(":checked") == true) {
                    dataItem.MeetingAviability[j].AviabilityResponses = true;
                }
                else if($(item).is(":checked") == false)
                {
                    dataItem.MeetingAviability[j].AviabilityResponses = false;
                }
                dataItem.dirty = true;
            }
        }
        $("#chjnotavailable" + dataItem.uid).prop("checked", false)
    }

    function setDataItemforNotavlMeeting(item)
    {
        
        var grid = $("#SeekAviabilityMeeting").data("kendoGrid");
        var row = $(item).closest("tr")
        var dataItem = grid.dataItem(row);

        for (j = 0; j < dataItem.MeetingAviability.length > 0; j++) {
            var currentitem = $("#" + item.id);
            var id = '#' + j + dataItem.uid + '_checkbox';

                if ($(item).is(":checked") == true) {
                    dataItem.MeetingAviability[j].AviabilityResponses = false;
                    dataItem.MeetingAviability[j].notAvialabel = true;
                    $("#" + j + dataItem.uid + "_checkbox").prop("checked",false)
                }
                else if ($(item).is(":checked") == false) {
                    dataItem.MeetingAviability[j].notAvialabel = false;
                }
                dataItem.dirty = true;
                //+ i + data.uid + "_checkbox

        }
    }
    function saveseekavailibilityresponse(item)
    {
        var grid = $("#SeekAviabilityMeeting").data("kendoGrid");
        kendo.ui.progress(grid.element, true);
        var notification = $("#staticNotification").kendoNotification({
            position: {
                top: 50,
                right: 600,
                pinning: true,
                button: false,
                hideOnClick: false,
                autoHideAfter: 3500
            }
        }).data("kendoNotification");
        

        var row = $(item).closest("tr")
        var dataItem = grid.dataItem(row);
        var MeetingVM = [];
        var meetingAviability = []
        MeetingVM.push(dataItem);

        meetingAviability.push(dataItem.MeetingAviability)

        MeetingVM.push(dataItem);
        $.ajax({
            type: "POST",
            //
            url: '@Url.Action("UpdateAvailability", "DirectorMeetings")',
            data: JSON.stringify({ meetingAviability: JSON.stringify(dataItem.MeetingAviability) }),
            contentType: 'application/json; charset=utf-8',
            //dataType: "json",
            cache: false,
            success: function (data) {
                notification.show("Save successfully", "success");
                kendo.ui.progress(grid.element, false);
            }
        });

    }
    function GetMeetingsDetails(data) {
        
        var str = "";

        var color = "#017fbe";

        var day = moment(data.MeetingDated).format('DD');



        str += "<div style='padding-bottom:4px;margin:10px 10px;'><table cellpadding='0' cellspacing='0' style='width:100%;table-layout:fixed;'><tbody><tr><td style='vertical-align:top;width:55px;text-align:center;'><table cellpadding='0' cellspacing='0' style='width:50px;margin:0px auto;border:1px solid rgb(224, 224, 224);border-radius:5px;'><tbody><tr><td style='background-color:#017fbe;color:#ffffff;font-size:15px;line-height:18px;border-radius:4px 4px 0px 0px;'></td></tr><tr><td style='color:#555555;font-size:20px;line-height:1;padding:5px 0px;'>?</td></tr></tbody></table></td><td style='padding:0px 30px 0px 15px;vertical-align:top;'><p style='line-height:1.4;'></p><p style='line-height:1.4;margin-bottom: 0px;font-weight:bold;'>" + data.EntityName + "</p><p style='line-height:1.4;'><h1 style='cursor:pointer;font-size:16px;line-height:1.4;margin-top:0px;padding-bottom: 0px;margin-bottom: 0px;font-weight:bold;'>" + data.MeetingTypeName + " Meeting</h1></p></td></tr></tbody></table></div><div class='row colpadding0 mt30'><div class='col-md-12 colpadding0'style='text-align:left'> <button type='button' id='checkcalender" + data.uid + "' class='btn btn-primary checkcalender ml-8 hidden' onclick='checkcalender(this)'>Check calendar</button></div></div>";


        return str;
    }

    function GetSeekAviabilitydetails(data)
    {
        
        var i=0;
        var str1 = "";
        var str = "";
        var strbutton = "";
        if(data.MeetingAviability.length>0)
        {
            str= "<label class='control-label'>Select your availability</label>"
            for(i=0;i<data.MeetingAviability.length;i++)
            {
                str1 += "<div class='row colpadding0 mt-1'><div class='col-md-12 colpadding0'><div class='col-md-1 colpadding0 mt-1'><input type='checkbox'Id='" + i + data.uid + "_checkbox' name='checkmarkavailibility'onchange='setDataItemforavlonMeeting(this);' value='" + data.MeetingAviability[i].AviabilityResponses + "'/></div><div class='col-md-6 colpadding0'><input type='hidden' name='hiddenMeetingId' value='" + data.MeetingAviability[i].MeetingId + "'/><input type='hidden' name='hiddenseekavailabilityId' value='" + data.MeetingAviability[i].meetingavaiId + "'/><label class='seekavalablefont'>" + data.MeetingAviability[i].seekavadate + "</label></div><div class='col-md-4 colpadding0'><label class='seekavalablefont'>" + data.MeetingAviability[i].seekavaTime + "</label></div></div></div>"
            }
            str1 += "<div class='row colpadding0 mt-1'><div class='col-md-12 colpadding0'><div class='col-md-1 colpadding0 mt-1'><input type='checkbox' name='checkmarkavai' id='chjnotavailable" + data.uid + "' onchange='setDataItemforNotavlMeeting(this);'/></div><div class='col-md-11 colpadding0'><label class='seekavalablefont'>Not available on either of any above dates</label></div></div></div>"
            strbutton = "<div class='row colpadding0 mt30'><div class='col-md-12 colpadding0'style='text-align:left'> <button type='button' id='seekaviability" + data.uid + "' class='btn btn-primary seekavabtn ml-8' onclick='saveseekavailibilityresponse(this)'>Save</button></div></div>"
        }
        return str + str1 + strbutton;
    }
    function onRowBound() {
        var grid = $("#SeekAviabilityMeeting").data("kendoGrid");
        var data = grid.dataSource.data();
        var gridData = grid.dataSource.view();
        $.each(data, function (i, row) {
            $('tr[data-uid="' + row.uid + '"] ').removeClass("k-alt");

            $('tr[data-uid="' + row.uid + '"] ').css("box-sizing", "border-box");
            $('tr[data-uid="' + row.uid + '"] ').css("box-shadow", "0px 0px 2px 0 #DDDDDD");
            $('tr[data-uid="' + row.uid + '"] ').css("height", "187px");
        })

        for (var i = 0; i < gridData.length; i++)
        {
            var currentUid = gridData[i].uid;
            if (gridData[i].MeetingAviability.length > 0) {
              
                for (var j = 0; j < gridData[i].MeetingAviability.length; j++) {
                 
                    var unceheckedboxid = $("#chjnotavailable" + currentUid);
                    var checkboxid = $("#" + j + currentUid + "_checkbox");
                    if (gridData[i].MeetingAviability[j].ResponseAviabilityId > 0)
                    {
                        if (gridData[i].MeetingAviability[j].AviabilityResponses)
                        {
                            checkboxid.prop('checked', true);
                            unceheckedboxid.prop('checked', false);
                        }
                        else
                        {
                            unceheckedboxid.prop('checked', true);
                            checkboxid.prop('checked', false);
                        }
                        $("#seekaviability" + currentUid).hide();
                    }
                    else
                    {
                        checkboxid.prop('checked', false);
                        unceheckedboxid.prop('checked', false);
                        $("#seekaviability" + currentUid).show();
                    }
                }
                
            }
            else
            {
                //$("#seekaviability" + currentUid).show();
            }

        }
    }

</script>
<div class="row colpadding0">
    <div class="col-md-12 colpadding0">
        <span id="staticNotification"></span>
    </div>
</div>

<div class="row colpadding0 mt30">
    <div class="col-md-12 colpadding0">

        @(Html.Kendo().Grid<BM_ManegmentServices.VM.MeetingVM>()
        .Name("SeekAviabilityMeeting")
        .Columns(columns =>
        {

            columns.Bound(c => c.EntityName).Title("")
            .ClientTemplate("<div>#= GetMeetingsDetails(data)#</div>").HtmlAttributes(new { style = "width:45%" }).Sortable(false).Filterable(false);
            columns.Bound(c => c.MeetingID).Title("")

           .ClientTemplate("<div>#= GetSeekAviabilitydetails(data)#</div>");

        })
        .Events(e => e.DataBound("onRowBound"))

            .DataSource(dataSource => dataSource
            .WebApi()
            .PageSize(10)
            .ServerOperation(false)
            .Model(model =>
            {
                model.Id(o => o.MeetingID);

            })

          .Read(read => read.Action("Getdetailsofseekava", "DirectorMeetings"))

                          ).HtmlAttributes(new { @style = "width:100%" })
        )
    </div>
</div>