ComplianceManagement.Portal/Areas/BM_Management/Controllers/FileDataController.cs
using BM_ManegmentServices.Services.DocumentManagenemt;
using BM_ManegmentServices.VM;
using com.VirtuosoITech.ComplianceManagement.Portal.Common;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace com.VirtuosoITech.ComplianceManagement.Portal.Areas.BM_Management.Controllers
{
    public class FileDataController : Controller
    {
        IFileData_Service objIFileData_Service;
        IFileStorage_Service objIFileStorage_Service;

        public FileDataController(IFileData_Service objFileData_Service, IFileStorage_Service objFileStorage_Service)
        {
            objIFileData_Service = objFileData_Service;
            objIFileStorage_Service = objFileStorage_Service;

        }
        // GET: BM_Management/Document_Viewer
        public ActionResult Viewer()
        {
            return View();
        }

        public ActionResult DownloadFile(long id)
        {
            try
            {
                int userId = Convert.ToInt32(AuthenticationHelper.UserID);
                var result = objIFileData_Service.GetFile(id, userId);
                if (result.FileData != null)
                {
                    return File(result.FileData, "application/force-download", result.FileName);
                }
                else
                {
                    return PartialView("_FileNotFound");
                }
            }
            catch (Exception ex)
            {
                return PartialView("_FileNotFound");
            }
        }

        public ActionResult UploadFileOnFileStorage(long meetingId)
        {
            var model = new FileStorageDataVM();
            model.MeetingId = meetingId;
            return PartialView("_UploadFileOnFileStorage", model);
        }
        [HttpPost]
        public ActionResult UploadFile(FileStorageDataVM obj, long meetingId)
        {
            int customerId = Convert.ToInt32(AuthenticationHelper.CustomerID);
            objIFileStorage_Service.UploadFile(obj, meetingId, customerId);
            return PartialView("_UploadFileOnFileStorage", meetingId);
        }
        public ActionResult GetUploadedFilesByMeetingId([DataSourceRequest] DataSourceRequest request, long meetingId)
        {
            return Json(objIFileStorage_Service.GetUploadedFilesByMeetingId(meetingId).ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }
        public ActionResult DownloadFileFromStorage(long id)
        {
            try
            {
                var obj = objIFileStorage_Service.GetFileDetails(id);
                if(obj != null)
                {
                    string fileExtension = Path.GetExtension(obj.FileName);
                    string fileName = obj.FileName;
                    string path = obj.FilePath;
                    string fileNameNew = obj.FileKey + fileExtension;

                    CloudStorageAccount storageAccount = CloudStorageAccount.Parse(ConfigurationManager.AppSettings["StorageConnectionString"].ToString());
                    CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();

                    CloudBlobContainer container = blobClient.GetContainerReference(path);
                    CloudBlockBlob blockBlob = container.GetBlockBlobReference(fileNameNew);
                    MemoryStream memStream = new MemoryStream();
                    blockBlob.DownloadToStream(memStream);
                    return File(memStream.ToArray(), blockBlob.Properties.ContentType.ToString(), fileName);
                }
                else
                {
                    return PartialView("_FileNotFound");
                }
            }
            catch (Exception ex)
            {
                return PartialView("_FileNotFound");
            }
        }
    }
}

ComplianceManagement.Portal/Areas/BM_Management/Controllers/MyMeetingsController.cs
using BM_ManegmentServices.Services.Masters;
using BM_ManegmentServices.Services.Meetings;
using BM_ManegmentServices.Services.MyMeetings;
using BM_ManegmentServices.VM;
using com.VirtuosoITech.ComplianceManagement.Portal.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace com.VirtuosoITech.ComplianceManagement.Portal.Areas.BM_Management.Controllers
{
    public class MyMeetingsController : Controller
    {
        IMeeting_Service objIMeeting_Service;
        IMainMeeting objIMainMeeting;
        IMyMeetingsService objIMyMeetingsService;

        public MyMeetingsController(IMeeting_Service objMeeting_Service, IMainMeeting objMainMeeting, IMyMeetingsService objMyMeetingsService)
        {
            objIMeeting_Service = objMeeting_Service;
            objIMainMeeting = objMainMeeting;
            objIMyMeetingsService = objMyMeetingsService;
        }
        public ActionResult Index()
        {
            return View();
        }

        #region Upcomming Meetings
        public PartialViewResult AgendaView(long MeetingId, long ParticipantId)
        {
            int CustomerId = Convert.ToInt32(AuthenticationHelper.CustomerID);
            int UserID = Convert.ToInt32(AuthenticationHelper.UserID);
            var model = objIMeeting_Service.PreviewAgenda(MeetingId, CustomerId);
            if (model != null)
            {
                model.ParticipantID_ = ParticipantId;
            }
            return PartialView("_AgendaViewer", model);
        }

        [HttpPost]
        public ActionResult SaveAgendaComments(MeetingAgendaCommentVM meetingAgendaCommentVM)
        {
            int UserID = Convert.ToInt32(AuthenticationHelper.UserID);
            meetingAgendaCommentVM = objIMyMeetingsService.SaveAgendaComments(meetingAgendaCommentVM, UserID);

            return Json(meetingAgendaCommentVM, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GetAgendaComments(long participantId)
        {
            var model = objIMyMeetingsService.GetAgendaComments(participantId);
            return Json(model, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GetParticipantAgendaComments(long meetingId)
        {
            var model = objIMyMeetingsService.GetParticipantAgendaComments(meetingId);
            return Json(model, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Meetings RSVP Details
        public PartialViewResult Meeting_RSVP_Details(long meetingId)
        {
            return PartialView("_RSVP_Details", meetingId);
        }
        #endregion

        #region Draft Minutes
        public ActionResult DraftMinutes()
        {
            return View();
        }

        public PartialViewResult DraftMinutesView(long MeetingId, long DraftCirculationID)
        {
            int CustomerId = Convert.ToInt32(AuthenticationHelper.CustomerID);
            int UserID = Convert.ToInt32(AuthenticationHelper.UserID);
            var model = objIMeeting_Service.PreviewDraftMinutes(MeetingId, CustomerId, DraftCirculationID, UserID);
            if (model != null)
            {
                model.DraftCirculationID_ = DraftCirculationID;
                model.IsDraftMinutesApproved = objIMeeting_Service.IsDraftMinutesApproved(DraftCirculationID);
                model.lstMeetingAttendance = objIMainMeeting.GetPerticipenforAttendenceCS(MeetingId, CustomerId, UserID);
                model.meetingMinutesDetails = objIMeeting_Service.GetMinutesDetails(MeetingId);
            }
            return PartialView("_DraftMinutesView", model);
        }
        [HttpPost]
        public ActionResult SaveComments(MeetingMinutesCommentVM meetingMinutesCommentVM)
        {
            int UserID = Convert.ToInt32(AuthenticationHelper.UserID);
            meetingMinutesCommentVM = objIMyMeetingsService.SaveComments(meetingMinutesCommentVM, UserID);

            return Json(meetingMinutesCommentVM, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ApproveDraftMinutes(MeetingMinutesApproveVM obj)
        {
            int UserID = Convert.ToInt32(AuthenticationHelper.UserID);
            obj = objIMeeting_Service.ApproveDraftMinutes(obj, UserID);

            return PartialView("_DraftMinutesApprove", obj);
        }

        [HttpPost]
        public ActionResult GetComments(long draftCirculationID)
        {
            var model= objIMyMeetingsService.GetComments(draftCirculationID);
            return Json(model, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GetParticipantComments(long meetingId)
        {
            var model = objIMyMeetingsService.GetParticipantComments(meetingId);
            return Json(model, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Concluded Meeting
        public ActionResult ConcludedMeetings()
        {
            return View();
        }

        public PartialViewResult MOM(long MeetingId, long DraftCirculationID)
        {
            int CustomerId = Convert.ToInt32(AuthenticationHelper.CustomerID);
            int UserID = Convert.ToInt32(AuthenticationHelper.UserID);
            var model = objIMeeting_Service.PreviewMOM(MeetingId, CustomerId);
            if (model != null)
            {
                model.lstMeetingAttendance = objIMainMeeting.GetPerticipenforAttendenceCS(MeetingId, CustomerId, UserID);
                model.meetingMinutesDetails = objIMeeting_Service.GetMinutesDetails(MeetingId);
            }
            return PartialView("_MOMView", model);
        }
        #endregion

        #region Agenda List of Concluded Meetings
        public ActionResult AgendaItems()
        {
            return View("ConcludedMeetingAgenda");
        }

        public ActionResult AgendaItems_CS()
        {
            return View("ConcludedMeetingAgenda_CS");
        }
        #endregion
    }
}

ComplianceManagement.Portal/Areas/BM_Management/Views/MyMeetings/DraftMinutes.cshtml
@using Kendo.Mvc.UI;
@using com.VirtuosoITech.ComplianceManagement.Portal.Common;
@{
    ViewBag.Title = "Draft Minutes";
}

<style>
    /*#DraftMinutes .k-grid-header {
        height: 0;
        border-bottom-width: 0;
        display: none;
        overflow: hidden;
    }*/

    .mt-1 {
        margin-top: 1%;
    }

    .seekavabtn {
        width: 11%;
        height: 25px;
        left: 1399px;
        top: 122px;
        background: #0090D6;
        border-radius: 5px;
    }

    .container .checkmarkava:after {
        left: 4px;
        top: 0px;
        width: 6px;
        height: 13px;
        border: solid #1976d2;
        border-width: 0 3px 3px 0;
        -webkit-transform: rotate(45deg);
        -ms-transform: rotate(45deg);
        transform: rotate(45deg);
    }
</style>

<!-- Agenda / MOM preview css-->
<style>
    .myHeading h3 {
        font-size: 1.2em;
        margin-top: 2px;
        text-align: center;
        color: #1f97f7;
        width: auto;
        font-weight: normal;
    }

    .myHeading h4 {
        font-size: 1.6em;
        /*text-transform: uppercase;*/
        text-align: center;
        font-weight: normal;
        /*color: #1f97f7;*/
        width: auto;
    }

    .myIndex h3 {
        font-size: 1.1em;
        margin-top: 1px;
        margin-left: 20px;
        text-align: left;
        width: auto;
        font-weight: normal;
    }

    #main-content-agenda-preview {
        display: table-cell;
        margin: 0;
        padding: 20px;
        /* width: 680px; */
        /*width: 980px;*/
        vertical-align: top;
    }

    .widget.placeholder {
        opacity: 0.4;
        border: 1px dashed #a6a6a6;
    }

    /* WIDGETS */
    .widget {
        margin: 0 0 10px;
        padding: 0;
        background-color: #ffffff;
        border: 1px solid #e7e7e7;
        border-radius: 3px;
        /*cursor: move;*/
    }


        .widget:hover {
            background-color: #fcfcfc;
            border-color: #cccccc;
        }

        .widget div {
            padding: 10px;
            min-height: 50px;
        }

        .widget h3 {
            font-size: 12px;
            padding: 8px 10px;
            text-transform: uppercase;
            border-bottom: 1px solid #e7e7e7;
            margin-top: 2px;
            text-align: right;
        }

            .widget h3 span {
                float: right;
            }

                .widget h3 span:hover {
                    cursor: pointer;
                    background-color: #e7e7e7;
                    border-radius: 20px;
                }

    /* BLOGS & NEWS */
    #blogs div,
    #news div {
        /*padding: 0 20px 20px;*/
        padding: 0 20px 1px;
    }

    #teammates h4,
    #blogs h4,
    #news h4 {
        width: auto;
        margin: 10px 0 2px;
        font-size: 1.4em;
        color: #1f97f7;
        font-weight: normal;
    }

    .blog-info {
        margin: 0 0 10px;
        font-size: .9em;
        color: #787878;
    }

    #sidebar #blogs h4 {
        font-size: 1em;
    }

    #sidebar #blogs p {
        display: none;
    }

    #sidebar #blogs .blog-info {
        display: block;
    }

    #main-content-agenda-preview #news h4 {
        font-size: 1.2em;
        line-height: 1.4em;
        height: 40px;
    }

        #main-content-agenda-preview #news h4 span {
            display: block;
            float: left;
            width: 100px;
            height: 40px;
            color: #000;
        }

    .hint {
        width: 250px;
        height: 100px;
        overflow: hidden;
    }

        .hint > h3 {
            padding-left: 20px;
        }
</style>

<style>
    .widget {
        margin-left: 50px;
        /*border-right-width: 0px;*/
        margin-bottom: 2px;
        margin-right: 50px;
    }

    #teammates h4,
    #blogs h4,
    #news h4 {
        /*margin-top :50px;*/
    }

    #blogs div,
    #news div {
        /*padding: 0 20px 20px;*/
        padding: 50px 90px 50px;
    }
</style>

<style>

    .page-thumb {
        /*padding: 5px 2px 5px;
    border: 1px;
    border-color: #c7c1c1;
    border-style: solid;
    margin-left: 5px;
    margin-right: 5px;
    max-height: 80px;
    padding-left:10px;*/
        padding: 20px 20px 20px;
        border: 1px;
        background-color: white;
        border-color: #c7c1c1;
        border-style: solid;
        margin-left: 20px;
        margin-right: 20px;
        /*max-height: 98px;
    padding-left: 10px;*/
        font-size: smaller;
        line-height: 1.5em;
    }
</style>

<!-- Draft Minutes Status-->
<style>
    .draft-status-label {
        color: #666;
    }
    .draft-status {
        text-align: center;
        /*margin-top: 2px;*/
        height: 21px;
        line-height: 1.6em;
        margin-left: 10px;
        margin-right: 10px;
        width: 20px;
    }
    .draft-status-received {
        background-color: #ffdcda;
        color: #b03830;
    }
    .draft-status-read {
        background-color: #ffefc7;
        color: #cf8224;
    }
    .draft-status-approved {
        background-color: #d7fccd;
        color: #259987;
    }
</style>

<script>

    function GetMeetingsDetails(data) {
        
        var str = "";

        var color = "#017fbe";

        //var day = moment(data.MeetingDate).format('DD');
        //var DateOfDraftCirculation = moment(data.DateOfDraftCirculation).format('DD/MM/YYYY');
        //        str += "<div style='padding-bottom:4px;margin:10px 10px;'><table cellpadding='0' cellspacing='0' style='width:100%;table-layout:fixed;'><tbody><tr><td style='vertical-align:top;width:55px;text-align:center;'><table cellpadding='0' cellspacing='0' style='width:50px;margin:0px auto;border:1px solid rgb(224, 224, 224);border-radius:5px;'><tbody><tr><td style='background-color:#017fbe;color:#ffffff;font-size:14px;line-height:12px;border-radius:4px 4px 0px 0px;'>" + data.Month + "</td></tr><tr><td style='color:#555555;font-size:20px;line-height:1;padding:5px 0px;'>" + data.Day + "</td></tr></tbody></table></td><td style='padding:0px 30px 0px 15px;vertical-align:top;'><h1 style='cursor:pointer;font-size:16px;line-height:1.4;margin-top:0px;padding-bottom: 0px;margin-bottom: 0px;font-weight:bold;'>" + data.MeetingTypeName + " Meeting</h1><p style='line-height:1.4;'></p><p style='line-height:1.4;margin-bottom: 0px;font-weight:bold;'>" + data.EntityName + "</p><p style='line-height:1.4;'></p></td></tr></tbody></table></div>";
        str = "<div style='padding-bottom:2px;margin:2px 2px;'><table cellpadding='0' cellspacing='0' style='width:100%;table-layout:fixed;'><tbody><tr><td style='vertical-align:top;width:55px;text-align:center;'><table cellpadding='0' cellspacing='0' style='width:50px;margin:0px auto;border:1px solid rgb(224, 224, 224);border-radius:5px;'><tbody><tr><td style='background-color:#017fbe;color:#ffffff;font-size:14px;line-height:12px;border-radius:4px 4px 0px 0px;'>" + data.Month + "</td></tr><tr><td style='color:#555555;font-size:20px;line-height:1;padding:5px 0px;'>" + data.Day + "</td></tr></tbody></table></td><td style='padding:0px 30px 0px 15px;vertical-align:top;'><h1 style='cursor:pointer;font-size:16px;line-height:1.4;margin-top:0px;padding-bottom: 0px;margin-bottom: 0px;font-weight:bold;'>" + data.MeetingTypeName + " Meeting [ " + data.MeetingSrNo + " ]</h1><p style='line-height:1.4;'></p><p style='line-height:1.4;margin-bottom: 0px;font-weight:bold;'>" + data.EntityName + "</p><p style='line-height:1.4;'></p></td></tr></tbody></table></div>";
        return str;
    }

    function onRowBound() {
        //var grid = $("#DraftMinutes").data("kendoGrid");
        //var data = grid.dataSource.data();
        //$.each(data, function (i, row) {
        //    $('tr[data-uid="' + row.uid + '"] ').removeClass("k-alt");

        //    $('tr[data-uid="' + row.uid + '"] ').css("box-sizing", "border-box");
        //    $('tr[data-uid="' + row.uid + '"] ').css("box-shadow", "0px 0px 2px 0 #DDDDDD");
        //    $('tr[data-uid="' + row.uid + '"] ').css("height", "187px");
        //})


    }
</script>

<script type="text/javascript">
    function showMinutesOfMeeting(e) {
        e.preventDefault();

        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        var direction = "@Url.Action("DraftMinutesView", "MyMeetings")" + "?MeetingId=" + dataItem.MeetingID + "&DraftCirculationID=" + dataItem.DraftCirculationID;

        //if (dataItem.IsMeetingCompleted == true) {

            $("#wndMOMPreview").attr("style", "min-height:100px;");

            var wnd = $("#wndMOMPreview").data("kendoWindow");
            var opts = wnd.options;

            wnd = $("#wndMOMPreview").kendoWindow({
                actions: ["Close"],
                content: direction,
                width: "85%",
                visible: false,
                modal: true,
                refresh: function () { this.center(); kendo.ui.progress(this.element, false); },
                open: function () { kendo.ui.progress(this.element, true); },
                close: function (e) {
                    
                   // var target = $('body .myComment');
                    //target.marker('destroy');
                    $(this.element).empty();
                    $('#DraftMinutes').data('kendoGrid').dataSource.read();
                }
            }).data("kendoWindow");
            opts.width = "85%";

            wnd.setOptions(opts);
            wnd.center();
            wnd.open();
        //}
    }
</script>

<script>
    function getUserDetails() {
         var loggedInUserID = '@AuthenticationHelper.UserID';
        var customerID = '@AuthenticationHelper.CustomerID';
        return {
            customerId: customerID, userId : loggedInUserID
        }
    }

    function GetDraftMinutesStatus(data) {
        
        var str = "";
        if (data.IsRead == false) {
            str = "<div class='draft-status draft-status-received'>&nbsp;</div>";
        }
        else if (data.IsApproved == true) {
            str = "<div class='draft-status draft-status-approved'>&nbsp;</div>";
        }
        else if (data.IsRead == true) {
            str = "<div class='draft-status draft-status-read'>&nbsp;</div>";
        }

        return str;
    }
</script>

<div class="row master-Headre" style="height:50px;">
    <div class="col-md-12 vertical-center">
        <div class="col-md-8 colpadding0">
        </div>
        <div class="col-md-4 colpadding0">
            <div class="col-md-4">
                <div class="col-md-4 colpadding0">
                    <div class='draft-status draft-status-received'></div>
                </div>
                <div class="col-md-8">
                    <span class="draft-status-label">Received</span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="col-md-4 colpadding0">
                    <div class='draft-status draft-status-read'></div>
                </div>
                <div class="col-md-8">
                    <span class="draft-status-label">Read</span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="col-md-4 colpadding0">
                    <div class='draft-status draft-status-approved'></div>
                </div>
                <div class="col-md-8">
                    <span class="draft-status-label">Approved</span>
                </div>

            </div>
        </div>
    </div>
</div>

<div class="row colpadding0 mt30">
    <div class="col-md-12 colpadding0">
        @(Html.Kendo().Window().Name("wndMOMPreview").Title("Draft Resolution & Minutes").Visible(false).Modal(true).Draggable(false).Scrollable(true))

        @(Html.Kendo().Grid<BM_ManegmentServices.VM.Dashboard.DraftMeetingListVM>
    ()
    .Name("DraftMinutes")
    .Columns(columns =>
    {
        columns.Bound(c => c.EntityName).Title("")
        .ClientTemplate("<div>#= GetMeetingsDetails(data)#</div>").HtmlAttributes(new { style = "width:70%" }).Sortable(false).Filterable(false).Title("Meeting");
        columns.Bound(c => c.DateOfDraftCirculation).ClientTemplate("#= GetDraftMinutesStatus(data)#").Title("");
        //columns.Bound(c => c.DateOfDraftCirculation).Title("");
        columns.Bound(p => p.DateOfDraftCirculation).ClientTemplate("#= DateOfDraftCirculation == null ? '' : kendo.toString(DateOfDraftCirculation, \"dd-MMM-yyyy\")#").HeaderTemplate("Received Date").Sortable(false).Width("12%");
        columns.Bound(p => p.DueDateOfDraftCirculation).ClientTemplate("#= DueDateOfDraftCirculation == null ? '' : kendo.toString(DueDateOfDraftCirculation, \"dd-MMM-yyyy\")#").HeaderTemplate("Due Date").Sortable(false).Width("12%");
        columns.Command(command =>
        {
            //command.Custom("MI").Click("showMinutesOfMeeting").HtmlAttributes(new { @class = "k-grid-mom" });
            command.Custom("D").Click("showMinutesOfMeeting").HtmlAttributes(new { @class = "k-grid-mom" });
        }).Title("Action");

    })
    .Events(e => e.DataBound("onRowBound"))

    .DataSource(dataSource => dataSource
    .WebApi()
    .PageSize(10)
    .ServerOperation(false)
    .Model(model =>
    {
        model.Id(o => o.MeetingID);
        model.Field(o => o.DraftCirculationID);
        model.Field(o => o.IsRead);
        model.Field(o => o.IsApproved);
    })

    .Read(read => read.Url("/api/MyMeetings/DraftMeetings").Data("getUserDetails"))

    ).HtmlAttributes(new { @style = "width:100%" })
    )
</div>
</div>

<script>
    $(document).ready(function () {

        var breadCrumbData = [
            {
                displayText: "My Meetings",
                navigateUrl: "#",
            },
            {
                displayText: "Draft Minutes",
                navigateUrl: "#",
            }
        ];

        setBreadCrumb(breadCrumbData);
    });
</script>

ComplianceManagement.Portal/Areas/BM_Management/Views/MyMeetings/Index.cshtml
@{
    ViewBag.Title = "Meetings";
}
@{ 
    var classForDirector = "";
    if(com.VirtuosoITech.ComplianceManagement.Portal.Common.AuthenticationHelper.Role == "DRCTR")
    {
        classForDirector = "hidden";
    }
}

ComplianceManagement.Portal/Areas/BM_Management/Views/MyMeetings/_DraftMinutesApprove.cshtml
@using Kendo.Mvc.UI;
@model BM_ManegmentServices.VM.MeetingMinutesApproveVM

<div id="divApproveDraftMinutes">

    @using (Ajax.BeginForm("ApproveDraftMinutes", "MyMeetings", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "divApproveDraftMinutes" }, new { id = "frmApproveDraftMinutes" }))
    {
        if (Model.Success)
        {
            <div class="row mt30">
                <div class="col-md-12 colpadding0" id="DivsuccessI_sub">
                    <div style="margin-left:2%; margin-right:2%;">
                        <div class="alert alert-success alert-dismissible">
                            <button class="close" type="button" onclick="hideAlert_Sub();">×</button>
                            <lable id="lblsuccessI_sub">@Model.Message</lable>
                        </div>
                    </div>
                </div>
            </div>
        }
        else if (Model.Error)
        {
        <div class="row mt30">
            <div class="col-md-12 colpadding0" id="DiverrorI_sub">
                <div style="margin-left:2%; margin-right:2%;">
                    <div class="alert alert-danger alert-dismissible">
                        <button class="close" type="button" onclick="hideAlert_Sub();">×</button>
                        <lable id="lblerrormsgI_sub">@Model.Message</lable>
                    </div>
                </div>
            </div>
        </div>
        }

            <div>
                @Html.HiddenFor(m => m.MeetingId)
                @Html.HiddenFor(m => m.DraftCirculationID)  
            </div>

            <div class="row mt30 hidden">
                <div class="col-md-8 colpadding0">
                    <div class="col-md-3 colpadding0">
                        <label class="control-label">Comment</label>
                    </div>
                    <div class="col-md-9 colpadding0">
                        
                        @Html.TextAreaFor(m => m.Comment, new { @class = "k-textbox", style = "width: 98%;", @spellcheck = "true" })
                        @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })

                    </div>
                </div>
               

                <div class="col-md-4 colpadding0">

                    <div class="col-md-3 colpadding0">
                        <label class="control-label">Comment</label>
                    </div>
                    <div class="col-md-9 colpadding0">
                        @Html.TextBoxFor(m => m.Files, new { type = "file", style = "width:100%" })
                        @Html.HiddenFor(m => m.Files)

                    </div>

                    
                   
                </div>

                @*@if (Model.FileDataId > 0)
                {
                    <a href='@Url.Action("DownloadFile", "FileData",new { id = Model.FileDataId} )' target="_blank">
                        <img src='@Url.Content("~/Images/icon-download.png")' />
                    </a>
                }*@
            </div>

            <div class="text-center mt30">
                <button type="submit" value="update" class="btn btn-primary button1">Approve</button>
            </div>
    }
</div>